# Generated by Django 5.0 on 2026-03-31 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaceType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("color", models.CharField(default="#007AFF", max_length=7)),
                ("icon", models.CharField(blank=True, max_length=50, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="place_types",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "place_types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "radius_m",
                    models.IntegerField(
                        blank=True,
                        help_text="Optional geofence radius in meters for arrival/departure inference",
                        null=True,
                    ),
                ),
                ("is_favorite", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="places",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "place_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="places",
                        to="locations.placetype",
                    ),
                ),
            ],
            options={
                "db_table": "places",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TravelMode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("color", models.CharField(default="#34C759", max_length=7)),
                ("icon", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "min_speed_mps",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "max_speed_mps",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travel_modes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "travel_modes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TravelSegment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "distance_m",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                (
                    "mode_confidence",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=4, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "destination_place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="travel_destination_segments",
                        to="locations.place",
                    ),
                ),
                (
                    "inferred_mode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inferred_travel_segments",
                        to="locations.travelmode",
                    ),
                ),
                (
                    "origin_place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="travel_origin_segments",
                        to="locations.place",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travel_segments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_selected_mode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_selected_travel_segments",
                        to="locations.travelmode",
                    ),
                ),
            ],
            options={
                "db_table": "travel_segments",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="VisitSegment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arrived_at", models.DateTimeField()),
                ("departed_at", models.DateTimeField(blank=True, null=True)),
                ("inferred", models.BooleanField(default=True)),
                (
                    "confidence",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=4, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visit_segments",
                        to="locations.place",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visit_segments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "visit_segments",
                "ordering": ["-arrived_at"],
            },
        ),
        migrations.CreateModel(
            name="LocationSample",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "accuracy_m",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "altitude_m",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "speed_mps",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Meters/second if available from device APIs",
                        max_digits=7,
                        null=True,
                    ),
                ),
                (
                    "heading_deg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("phone", "Phone"),
                            ("laptop", "Laptop"),
                            ("other", "Other"),
                        ],
                        default="phone",
                        max_length=20,
                    ),
                ),
                ("device_id", models.CharField(blank=True, max_length=128, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_samples",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "location_samples",
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "recorded_at"],
                        name="location_sa_user_id_efa3cb_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="placetype",
            index=models.Index(
                fields=["user", "name"], name="place_types_user_id_c8d2d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="placetype",
            index=models.Index(
                fields=["user", "is_active"], name="place_types_user_id_ca2a15_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="place",
            index=models.Index(
                fields=["user", "is_favorite"], name="places_user_id_8a77b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="place",
            index=models.Index(
                fields=["user", "name"], name="places_user_id_72bb39_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="place",
            unique_together={("user", "name")},
        ),
        migrations.AddIndex(
            model_name="travelmode",
            index=models.Index(
                fields=["user", "name"], name="travel_mode_user_id_6f4a4a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="travelmode",
            index=models.Index(
                fields=["user", "is_active"], name="travel_mode_user_id_24c79d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="travelsegment",
            index=models.Index(
                fields=["user", "started_at"], name="travel_segm_user_id_414f64_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visitsegment",
            index=models.Index(
                fields=["user", "arrived_at"], name="visit_segme_user_id_d56dc8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visitsegment",
            index=models.Index(
                fields=["place", "arrived_at"], name="visit_segme_place_i_27455e_idx"
            ),
        ),
    ]
