# Generated by Django 6.0.3 on 2026-05-01 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_alter_locationsample_id_alter_place_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arrived_at", models.DateTimeField()),
                ("departed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("radius_m", models.IntegerField(blank=True, null=True)),
                ("dwell_seconds", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visit_candidates",
                        to="locations.place",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visit_candidates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visit_segment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_candidates",
                        to="locations.visitsegment",
                    ),
                ),
            ],
            options={
                "db_table": "visit_candidates",
                "ordering": ["-arrived_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status", "arrived_at"],
                        name="visit_candi_user_id_f7e6c1_idx",
                    ),
                    models.Index(
                        fields=["user", "arrived_at"],
                        name="visit_candi_user_id_b7e1de_idx",
                    ),
                ],
            },
        ),
    ]
