# Generated by Django 5.0 on 2026-03-31 02:40

from django.db import migrations


DEFAULT_CURRENCIES = [
    {"code": "USD", "name": "US Dollar", "symbol": "$"},
    {"code": "ZAR", "name": "South African Rand", "symbol": "R"},
    {"code": "EUR", "name": "Euro", "symbol": "€"},
    {"code": "GBP", "name": "British Pound", "symbol": "£"},
]

DEFAULT_TRANSACTION_KINDS = [
    {"name": "expense"},
    {"name": "income"},
    {"name": "transfer"},
]


def seed_defaults(apps, schema_editor):
    Currency = apps.get_model("finance", "Currency")
    TransactionKind = apps.get_model("finance", "TransactionKind")

    for cur in DEFAULT_CURRENCIES:
        Currency.objects.get_or_create(code=cur["code"], defaults=cur)

    for kind in DEFAULT_TRANSACTION_KINDS:
        TransactionKind.objects.get_or_create(
            user=None,
            name=kind["name"],
            defaults={"visibility": "public", "is_active": True},
        )


def unseed_defaults(apps, schema_editor):
    Currency = apps.get_model("finance", "Currency")
    TransactionKind = apps.get_model("finance", "TransactionKind")

    Currency.objects.filter(code__in=[c["code"] for c in DEFAULT_CURRENCIES]).delete()
    TransactionKind.objects.filter(
        user=None,
        name__in=[k["name"] for k in DEFAULT_TRANSACTION_KINDS],
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_defaults, reverse_code=unseed_defaults),
    ]
