# Generated by Django 5.0 on 2026-03-31 02:46

from django.db import migrations


DEFAULT_CATEGORIES = [
    # Expenses
    {"name": "Food & Dining", "color": "#FF9500", "icon": "utensils", "visibility": "public"},
    {"name": "Groceries", "color": "#34C759", "icon": "cart", "visibility": "public"},
    {"name": "Transport", "color": "#007AFF", "icon": "car", "visibility": "public"},
    {"name": "Rent / Mortgage", "color": "#5856D6", "icon": "home", "visibility": "public"},
    {"name": "Utilities", "color": "#5AC8FA", "icon": "bolt", "visibility": "public"},
    {"name": "Entertainment", "color": "#AF52DE", "icon": "film", "visibility": "public"},
    {"name": "Health", "color": "#FF2D55", "icon": "heart", "visibility": "public"},
    {"name": "Shopping", "color": "#FF3B30", "icon": "bag", "visibility": "public"},
    {"name": "Subscriptions", "color": "#8E8E93", "icon": "repeat", "visibility": "public"},
    {"name": "Travel", "color": "#00C7BE", "icon": "plane", "visibility": "public"},

    # Income
    {"name": "Salary", "color": "#30D158", "icon": "briefcase", "visibility": "public"},
    {"name": "Bonus", "color": "#32D74B", "icon": "gift", "visibility": "public"},
    {"name": "Interest", "color": "#64D2FF", "icon": "percent", "visibility": "public"},
    {"name": "Refund", "color": "#0A84FF", "icon": "arrow-uturn-left", "visibility": "public"},
]

DEFAULT_PAYMENT_METHODS = [
    {"name": "Cash", "visibility": "public"},
    {"name": "Debit Card", "visibility": "public"},
    {"name": "Credit Card", "visibility": "public"},
    {"name": "Bank Transfer", "visibility": "public"},
    {"name": "Mobile Wallet", "visibility": "public"},
]


def seed_more_defaults(apps, schema_editor):
    FinanceCategory = apps.get_model("finance", "FinanceCategory")
    PaymentMethod = apps.get_model("finance", "PaymentMethod")

    for c in DEFAULT_CATEGORIES:
        FinanceCategory.objects.get_or_create(
            user=None,
            name=c["name"],
            defaults={
                "color": c.get("color", "#007AFF"),
                "icon": c.get("icon"),
                "visibility": c.get("visibility", "public"),
                "is_active": True,
            },
        )

    for pm in DEFAULT_PAYMENT_METHODS:
        PaymentMethod.objects.get_or_create(
            user=None,
            name=pm["name"],
            defaults={
                "visibility": pm.get("visibility", "public"),
                "is_active": True,
            },
        )


def unseed_more_defaults(apps, schema_editor):
    FinanceCategory = apps.get_model("finance", "FinanceCategory")
    PaymentMethod = apps.get_model("finance", "PaymentMethod")

    FinanceCategory.objects.filter(
        user=None,
        name__in=[c["name"] for c in DEFAULT_CATEGORIES],
    ).delete()

    PaymentMethod.objects.filter(
        user=None,
        name__in=[p["name"] for p in DEFAULT_PAYMENT_METHODS],
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0002_seed_defaults"),
    ]

    operations = [
        migrations.RunPython(seed_more_defaults, reverse_code=unseed_more_defaults),
    ]
